server:
  port : 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ajith
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use 'none' in production to avoid schema auto-creation
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true




